export const PASSPORT_STATUS = {
  ACTIVE: "ACTIVE",
  TRANSFER_PENDING: "TRANSFER_PENDING",
  ARCHIVED: "ARCHIVED",
  RESTRICTED: "RESTRICTED",
  INTEGRITY_WARNING: "INTEGRITY_WARNING",
};

export const PASS_PORT_STATUS = PASSPORT_STATUS;

export const PASSPORT_REVISION_STATE = {
  DRAFT: "DRAFT",
  PENDING_REVIEW: "PENDING_REVIEW",
  ACCEPTED: "ACCEPTED",
  ACCEPTED_WITH_WARNING: "ACCEPTED_WITH_WARNING",
  REJECTED: "REJECTED",
  SUPERSEDED: "SUPERSEDED",
  CONFLICTED: "CONFLICTED",
};

export const PASSPORT_CHANGE_OPERATION = {
  ADD: "ADD",
  UPDATE: "UPDATE",
  SUPERSEDE: "SUPERSEDE",
  RESOLVE: "RESOLVE",
  LINK: "LINK",
  UNLINK: "UNLINK",
  ANNOTATE: "ANNOTATE",
};

export const PASSPORT_INGESTION_STATE = {
  RECEIVED: "RECEIVED",
  VALIDATING: "VALIDATING",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
  CONFLICTED: "CONFLICTED",
  ACCEPTED: "ACCEPTED",
  ACCEPTED_WITH_WARNING: "ACCEPTED_WITH_WARNING",
  REJECTED: "REJECTED",
  BLOCKED: "BLOCKED",
};

export const PASSPORT_CONFLICT_STATE = {
  OPEN: "OPEN",
  UNDER_REVIEW: "UNDER_REVIEW",
  RESOLVED_ACCEPT_CANDIDATE: "RESOLVED_ACCEPT_CANDIDATE",
  RESOLVED_KEEP_CANONICAL: "RESOLVED_KEEP_CANONICAL",
  RESOLVED_MERGE: "RESOLVED_MERGE",
  RESOLVED_SUPERSEDE: "RESOLVED_SUPERSEDE",
  ACCEPTED_DIFFERENCE: "ACCEPTED_DIFFERENCE",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
};

export const PASSPORT_REBASE_STATE = {
  CLEAN: "CLEAN",
  CONFLICTED: "CONFLICTED",
  STALE: "STALE",
  BLOCKED: "BLOCKED",
  READY: "READY",
};

export const PASSPORT_RELATIONSHIP_TYPE = {
  OWNER: "OWNER",
  CO_OWNER: "CO_OWNER",
  TRUST: "TRUST",
  PROPERTY_MANAGER: "PROPERTY_MANAGER",
  TENANT: "TENANT",
  AUTHORIZED_AGENT: "AUTHORIZED_AGENT",
  CONTRACTOR: "CONTRACTOR",
  INSURER: "INSURER",
  LENDER: "LENDER",
  OTHER: "OTHER",
};

export const PASSPORT_COMPONENT_TYPE = {
  ROOF: "ROOF",
  ROOF_PLANE: "ROOF_PLANE",
  DECKING: "DECKING",
  FLASHING: "FLASHING",
  GUTTER: "GUTTER",
  DOWNSPOUT: "DOWNSPOUT",
  SIDING: "SIDING",
  WINDOW: "WINDOW",
  DOOR: "DOOR",
  FOUNDATION: "FOUNDATION",
  WALL: "WALL",
  ATTIC: "ATTIC",
  INSULATION: "INSULATION",
  HVAC: "HVAC",
  WATER_HEATER: "WATER_HEATER",
  PLUMBING: "PLUMBING",
  ELECTRICAL: "ELECTRICAL",
  SOLAR: "SOLAR",
  DRAINAGE: "DRAINAGE",
  APPLIANCE: "APPLIANCE",
  OTHER: "OTHER",
};

export const PASSPORT_COMPONENT_LIFECYCLE = {
  OBSERVED: "OBSERVED",
  ACTIVE: "ACTIVE",
  REPAIR_RECOMMENDED: "REPAIR_RECOMMENDED",
  UNDER_REPAIR: "UNDER_REPAIR",
  REPAIRED: "REPAIRED",
  REPLACED: "REPLACED",
  REMOVED: "REMOVED",
  UNKNOWN: "UNKNOWN",
};

export const PASSPORT_CONDITION_STATE = {
  ACTIVE: "ACTIVE",
  WATCH: "WATCH",
  IMPROVING: "IMPROVING",
  WORSENING: "WORSENING",
  RESOLVED: "RESOLVED",
  SUPERSEDED: "SUPERSEDED",
  DISPUTED: "DISPUTED",
  UNKNOWN: "UNKNOWN",
};

export const PASSPORT_INTEGRITY = {
  CLEAN: "CLEAN",
  WARNING: "WARNING",
  FAILURE: "FAILURE",
};

export const PASSPORT_ALERT_TYPE = {
  INGESTION_BLOCKED: "PASSPORT_INGESTION_BLOCKED",
  CONFLICT_CREATED: "PASSPORT_CONFLICT_CREATED",
  REVIEW_REQUIRED: "PASSPORT_REVIEW_REQUIRED",
  INTEGRITY_WARNING: "PASSPORT_INTEGRITY_WARNING",
  REBASE_REQUIRED: "PASSPORT_REBASE_REQUIRED",
  OWNERSHIP_TRANSFER_PENDING: "OWNERSHIP_TRANSFER_PENDING",
  BROKEN_SOURCE_REFERENCE: "BROKEN_SOURCE_REFERENCE",
  CANDIDATE_STALE: "CANDIDATE_STALE",
};

export const PASSPORT_DIRECTORY_FILTER = {
  ALL: "ALL",
  PENDING_REVIEW: "PENDING_REVIEW",
  OPEN_CONFLICTS: "OPEN_CONFLICTS",
  INTEGRITY_WARNING: "INTEGRITY_WARNING",
  TRANSFER_PENDING: "TRANSFER_PENDING",
  RECENTLY_UPDATED: "RECENTLY_UPDATED",
  BLOCKED_INGESTION: "BLOCKED_INGESTION",
};

export const PASSPORT_TWIN_TYPE = {
  TWIN_TYPE_A: "TWIN_TYPE_A",
  TWIN_TYPE_B: "TWIN_TYPE_B",
  TWIN_TYPE_C: "TWIN_TYPE_C",
};

export const PASSPORT_TWIN_STATUS = {
  APPROVED: "APPROVED",
  CURRENT: "CURRENT",
  HISTORICAL: "HISTORICAL",
  SUPERSEDED: "SUPERSEDED",
  UNAPPROVED: "UNAPPROVED",
  REJECTED: "REJECTED",
};

export const PASSPORT_PRIVATE_SCOPE = {
  EXCLUDE: "EXCLUDE",
  REDACT: "REDACT",
};
